### ISSUE TITLE
`0.2-release` doesn't compile with more recent nightly

### ISSUE THREAD

**Issue by bovee** [cargonauts-rs/cargonauts#19]
There's an issue with `max()` being implemented in both the standard library and in (a presumably older version of) `petgraph` that's causing an error when building the 0.2 version of _cargonauts_ now. This is only an issue because this is the branch installed by default with the CLI tool so the getting started experience was a little rocky.

Changing the autogenerated Cargo.toml file from `branch = "0.2-release"` to `branch = "master"` fixes it (so this should hopefully close whenever the next release is pinned in the CLI).

**Comment by withoutboats** [comment]
Updated `0.2-release` (shouldn't have been any breaking changes). Thanks for reporting this!
