### ISSUE TITLE
cargonauts needs CI

### ISSUE THREAD

**Issue by withoutboats** [cargonauts-rs/cargonauts#3]
I've been manually confirming that the tests are green before committing, but I should really set up CI sooner or later to make sure I never miss a commit.

**Comment by gentle-noah** [comment]
Travis seems to have solid support for Rust. I'd be willing to take a stab at getting this set up?

**Comment by withoutboats** [comment]
That would be cool :)

**Comment by withoutboats** [comment]
@gentle-noah One thing that would be great that doesn't need to involve Rust is a way to do integration testing of the examples.

Right now I manually run the examples and curl them. It would be great to have a little harness that could automatically boot them and make requests and test the responses. This is just a part of the testing framework so it doesn't need to be in Rust; Ruby seems like a great choice because I'd love to be able to write those tests in rspec or something.

**Comment by withoutboats** [comment]
I did this :-)
